"""add cache invalidations outbox

Revision ID: 50de5a0fa47d
Revises: bd87234ae927
Create Date: 2026-09-13 22:26:12.147854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50de5a0fa47d'
down_revision: Union[str, Sequence[str], None] = 'bd87234ae927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_invalidations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache_invalidations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache_invalidations')
    # ### end Alembic commands ###
