"""replace book_genres with genre_moods

Revision ID: bd87234ae927
Revises: 6650e425c991
Create Date: 2026-06-17 15:43:18.842107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bd87234ae927'
down_revision: Union[str, Sequence[str], None] = '6650e425c991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TIMESTAMPED_TABLES = ('authors', 'genres', 'users', 'books', 'user_profiles')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genres')
    op.create_table('moods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moods'))
    )
    op.create_index('uq_moods_name_active', 'moods', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('genre_moods',
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.Column('mood_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_genre_moods_genre_id_genres'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name=op.f('fk_genre_moods_mood_id_moods'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genre_id', 'mood_id', name=op.f('pk_genre_moods'))
    )
    for table in _TIMESTAMPED_TABLES:
        op.alter_column(
            table, 'updated_at',
            existing_type=sa.DateTime(timezone=True),
            nullable=True,
            existing_nullable=False,
            server_default=None,
            existing_server_default=sa.text('now()'),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in _TIMESTAMPED_TABLES:
        op.execute(f'UPDATE {table} SET updated_at = created_at WHERE updated_at IS NULL')
        op.alter_column(
            table, 'updated_at',
            existing_type=sa.DateTime(timezone=True),
            nullable=False,
            existing_nullable=True,
            server_default=sa.text('now()'),
            existing_server_default=None,
        )
    op.drop_table('genre_moods')
    op.drop_index('uq_moods_name_active', table_name='moods', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('moods')
    op.create_table('book_genres',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_genres_book_id_books'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_genres_genre_id_genres'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name=op.f('pk_book_genres'))
    )
    # ### end Alembic commands ###
