"""add user_memberships and membership_requests

Revision ID: f821de0f2d63
Revises: 50de5a0fa47d
Create Date: 2026-09-30 18:22:50.123346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f821de0f2d63'
down_revision: Union[str, Sequence[str], None] = '50de5a0fa47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_memberships_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_memberships')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_memberships_user_id'))
    )
    op.create_table('membership_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_membership_requests_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_membership_requests'))
    )
    op.create_index(op.f('ix_membership_requests_next_attempt_at'), 'membership_requests', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        'INSERT INTO membership_requests (user_id) '
        'SELECT id FROM users WHERE is_deleted = false'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_requests_next_attempt_at'), table_name='membership_requests')
    op.drop_table('membership_requests')
    op.drop_table('user_memberships')
    # ### end Alembic commands ###
